name: apod_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  file_saver: ^0.2.9
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
    
  #modules/packages
  apod_data:
    path: packages/apod_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
